### ISSUE TITLE
Issue with fitting a descriptors model

### ISSUE THREAD

**Issue by pikulsomesh** [pcko1/Deep-Drug-Coder#2]
I was trying to train a custom model with descriptors. I am able to set up a blank model using 
```
model = ddc.DDC(x = descriptors,
                                y = mols_in,
                                scaling        = True,
                                pca            = False,
                                dataset_info   = info,
                                noise_std      = 0.1,
                                lstm_dim       = 64,
                                dec_layers     = 3,
                                td_dense_dim   = 0,
                                batch_size     = 100)
```

But when trying to fit it using - 
```
model.fit(
    epochs=100,
    lr=1e-3,
    mini_epochs=10,
    patience=0.5,
    model_name='check',
)
```

I run into the error - 
`AttributeError: 'CodeGenerator' object has no attribute 'shape'`

I am able to use the demo notebooks provided in the repository, so ruling out that there are no dependency issues.

**Comment by pcko1** [comment]
Hi, this is an issue related to `tensorflow 2.x` being backwards incompatible with its previous version `1.12` that we originally used to develop our code. I have patched the issue in the `nightly` branch for anybody interested in retraining our models, kindly pull and switch to that branch and let me know if there are any persistent issues on your end. Thanks!

**Comment by JinChengneng** [comment]
Thanks for your help! however, this issue still occurs in the latest ```nightly``` branch, with the repeated messages ``` 'SVC' object  has no attribute '_probA' ```. The version of my ```tensorflow``` is 2.0.0.  I would appreciate it if you could recheck this problem and provide a complete config file ```ddc_env.yml```.

**Comment by pcko1** [comment]
Hi Jin,

The full environment specifications are found in the *ddc_env.yml* and
*setup.py* files:

https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/env/ddc_env.yml
https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/setup.py

If you follow the installation instructions in the README file carefully,
you should end up with a working environment with no need to install any
other python packages.

The problem that you are referring to is something I haven't personally
seen before but it seems related to the scikit-learn version that you have
installed. The one used in the ddc package is *0.21.3 *as seen in the
setup.py file.

Hope this helps!

Best,
/Pan
