### ISSUE TITLE
Reproducing demo_heteroencoder

### ISSUE THREAD

**Issue by bokertof** [pcko1/Deep-Drug-Coder#3]
Hello! I'm trying to reproduce steps in demo_heteroencoder file. However, I faced an issue at this point: 
`latent = model.transform(model.vectorize(mols_in))`
Instead of normal behaviour I get the following error:

```
InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNV2' used by {{node mol_to_latent_model/bidirectional_1/forward_Encoder_LSTM_1/CudnnRNNV2}} with these attrs: [seed=0, dropout=0, input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]

[[mol_to_latent_model/bidirectional_1/forward_Encoder_LSTM_1/CudnnRNNV2]] [Op:__inference_predict_function_10745]
```

I changed tensorflow to 1.13.0 version but it didn't help

**Comment by pcko1** [comment]
Hi, kindly make sure that your notebook instance has access to a GPU. This error usually implies that access to GPU has not been granted.  A way of checking using `tensorflow` 2+ is by running `tf.test.is_gpu_available`.

Source: https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available

**Comment by pcko1** [comment]
This is usually a CUDA driver issue that cannot be resolved with a conda environment, kindly make sure that your local CUDA drivers *and* cuDNN library installation are version 10.0 or above.

Also make sure that tensorflow has access to the gpu within your notebook instance by running `tf.test.is_gpu_available`.
