### ISSUE TITLE
Will the demos of model training be added in the future?

### ISSUE THREAD

**Issue by JinChengneng** [pcko1/Deep-Drug-Coder#4]
Hi there, thanks for your efforts to Deep Drug Coder and the demos of using models ```cRNN``` and ```heteroencoder``` are really helpful. However, demos of training these models, which are essential, are not provided in this repository. I wonder would this important part be added in the near future?

**Comment by pcko1** [comment]
Hi, the demos for re-training the models from scratch may be found under the `nightly` [branch](https://github.com/pcko1/Deep-Drug-Coder/tree/nightly).
