### ISSUE TITLE
message 'SVC' object has no attribute '_probA' arises while training a new model

### ISSUE THREAD

**Issue by JinChengneng** [pcko1/Deep-Drug-Coder#5]
Hi there! I am trying to run ```demo_cRNN_train.ipynb``` to train a new model. However, there arises a great number of messages saying that ```'SVC' object has no attribute '_probA'``` which is similar to [issue#2](https://github.com/pcko1/Deep-Drug-Coder/issues/2). I have sticked my ```numpy``` version to ```1.16.5``` and ```tensorflow-gpu``` to ```2.0.0``` according to ```README``` but it still doesn't work. I would appreciate it if you could recheck this problem and provide a complete config file ```ddc_env.yml```.

**Comment by pcko1** [comment]
Hi Jin, 

The full environment specifications are found in the ddc_env.yml and setup.py files:

https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/env/ddc_env.yml 
https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/setup.py 

If you follow the installation instructions in the README file carefully, you should end up with a working environment with no need to install any other python packages. The problem that you are referring to is something I haven't personally seen before but it seems related to the scikit-learn version that you have installed. The one used in the ddc package is 0.21.3 as seen in the setup.py file.

Hope this helps!

**Comment by JinChengneng** [comment]
I've checked the version of ```scikit-learn``` and it works successfully now. Thank you very much for your helpful response!
